minimum_pre_commit_version: "3.6.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck --severity=warning
        language: system
        types: [shell]
      - id: ruff-check
        name: ruff check
        entry: .venv/bin/ruff check
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format check
        entry: .venv/bin/ruff format --check
        language: system
        types: [python]
      - id: clang-format
        name: clang-format check
        entry: clang-format --dry-run --Werror
        language: system
        types_or: [c, c++]
